index.js

Firefox disables user selection on `disabled` form elements. To enable user selection across browsers we should use the `readOnly` attribute on the editor instead.

Support editor user-selection in Firefox

---

components/Editor.js

Attempted fix for issue #66 shamelessly taken from a recent PR for Prism:
https://github.com/PrismJS/prism/pull/1845/files
Have not yet tested on enough packages to be completely confident, but it looks promising and seems to work as expected for `?svelte@3.3.0/internal.js`. 
Keeping "[DO NOT MERGE YET]" in title until I've checked several packages: don't want code reviewers to get the impression that I've tested this much yet.

Fix for nested template string issue > #66

---

.sail.yml
components/Aside.js
cypress.json
cypress/integration/integration_spec.js
package.json

So I had a brain-spark this morning and I'm kinda annoyed I didn't think of it before!
So with Cypress we were having issues with the electron-browser doing es6 module imports from unpkg.com but it worked with chrome browser.
Soooo as sail.ci works with docker, why not just pull in a docker image which has chrome + node installed 🤯.
So this branch does that and everything worksgit add .
Also fixes failing cypress tests.

Cypress CI integration.

---

index.html

Quick fix: 
[Article on defer with es6 modules](https://developers.google.com/web/fundamentals/primers/modules#defer)
1. Removed defer as redundant (ran through w3c validator trying to fix edge)

FixForScriptTag

---

utils/recursiveDependencyFetch.js

This fixes #60 
1. Changed fetching of files + package.jsons to use a class which maintains its own map of what it has fetched. Resulting in IMO more comprehendible code and it fixes duplications of the same dependency being fetched. 
1. Wrote some additional documentation where I can.
I'm not big on using classes at the best of times but the classes created are within the recursivedependencyfetch function scope and feel nicer to read than the previous currying + self-invocation. 
Happy to hear thoughts.

Dedupe dependency fetching in recursiveDependencyFetch.

---

components/Article.js
components/Aside.js
components/Editor.js
cypress/integration/integration_spec.js
index.js
utils/makePath.js
utils/pushState.js
utils/recursiveDependencyFetch.js

So this is a big change to the editor component to do #43.
Essentially if you click on any import inline it will take you to that file. 
My initial approach was to bake this into the parser which was fun. But @VirtualDOMinic pointed out that this wasn't really the 'react' way and meant we had potentially two sources of truth for our dependencies. 
So we added a context `DependencyContext` to provide a source of truth for our dependencies in Editor.js. 
Our recursive dependency fetch would push its cache to `DependencyContext` when finished then our Editor.js consumes the data in its own `anchorAppender` function.
`anchorAppender` maps through dependencies and adds anchor tags to elements with imports/requires/exports that matched the dependencies.
This only runs when the Editor.js …

Clickable imports

---

components/Editor.js
index.js
utils/recursiveDependencyFetch.js

Contributes to (but does not fully close/fix) #64 
Compare sidebar for Svelte on this branch vs master to see effect of this
Seems to work fine!
Doesn't fix the clickable imports issue on Svelte, but I have come to the conclusion that it's out of scope. Think it'll over-complicate our app and a few things I tried seem pretty shaky... Will add to the discussion on #64 to explain more

Fix Svelte file resolution by assuming current path is a file, not a dir #64

---

components/Aside.js
components/Footer.js
index.css

See #96 
Changes:
- slight but noticeable reduction in aside width
- word wrapping in nav bar
- hide horizontal overflow in nav
Note:
I was unable to figure out how to make dependency paths in the aside (the right hand section) wrap! If anyone has any ideas/has a fix, please suggest/commit it :)

Changes to sidebars (nav and aside) #96

---

components/Aside.js
components/Nav.js
components/Search.js
index.js

This PR cleans up a bunch of our state continuing from #91.
It puts all our useStates in the index.js into a useReducer state object. 
We can also remove the dependency context. 
This for me feels much easier to comprehend and maintain. 
Interested in opinions, especially whether we're okay with Search and others having their own localised state (IMO it's fine).

Refactor state to use useReducer.

---

components/Overlay.js
index.css
index.html

@kiraarghy @VirtualDOMinic 
I noticed that `runpkg` was using an older version of our social share cards. 
This PR
- updates the social image to: https://formidable.com/static/social-preview.0eb61d35.png
- makes the formidable logo on the main page link back to formidable.com

Update social share cards, add link back

---

components/Nav.js
cypress/integration/integration_spec.js

- Modified the `changeVersion` regex to grab everything after the first path segment (package and version)
- Added test
Fixes #107

Fix changing from a suffixed version

---

index.js

1. Fixed to get versions from mirror rather than parsing unpkg.com.
Seems to be faster too.

Issue #126  More reliable package versions grabbing

---

package.json
tests/utils/parseUrl.test.js
utils/parseUrl.js
utils/recursiveDependencyFetch.js
yarn.lock

Added new parseUrl which should be able to parse most unpkg urls we come across as per #115 .
Tested in the following codesandbox https://codesandbox.io/s/jest-test-r3kjb
Should we make it that it only outputs the following object when it has all of those or make some of them nullable? i.e. so you can do `https://unpkg.com/@scope/pkg` not just `https://unpkg.com/@scope/pkg@1.0.0-beta.1/index.js`?
```
{
name,
version,
path,
file,
};
```

kara/nonStandardVersionFix #115

---

components/Article.js
components/Editor.js
reset.css

Adds a loading state for the editor for when we are fetching a new file + parsing dependencies.
Also adds scrolling to the selected line number on load.
Up for debate: Maybe we could move this logic to the context provider so all areas that use file info could have access to a loading state (i.e. the side panel could also have a loading state)

Editor loading state + Scroll to selected line

---

components/Article.js
index.html

If the article panels comes across a file that ends with `.md` then use [`marked`](https://github.com/markedjs/marked) to render it instead of showing the source code.

Render markdown files

---

components/Article.js
components/Editor.js
components/Main.js
index.js
utils/recursiveDependencyFetch.js

Moves `code` part of state into the appropriate cache entry for the given resource (also adds `extension` too). This makes inferring if we are waiting for code to be fetched easier, thus making the logic in `Editor` much simpler.

Moves code into cache and tidies up code loading state

---

components/Main.js
utils/recursiveDependencyFetchWorker.js

Recursion is hard (and deep dependency fetching is expensive) so ideally we should only do it when the user has asked for it; perhaps a button on the file tab could kick it off?
Discussion and experimentation required!

Dont recur by default

---

components/Editor.js

There is a case when rendering links in the editor; we check for the existence of a package in the `fileData.dependencies` object in order to determine wether to make it a link or not, the problem occurred when the package name was `toString` because objects have a `toString` method and so `fileData.dependencies['toString']` was returning the native code for that function and was thus truthy. This meant that `dep.replace` was not a function and caused a crash.
I put a check in to make sure that a string was returned from `fileData.dependencies['toString']` but if anyone has any better suggestions then I'm all ears!
Reproduction URL: `/?ramda@0.26.1/dist/ramda.min.js`
Fixed: https://deploy-preview-153--runpkg.netlify.com/?ramda@0.26.1/dist/ramda.min.js

Prevents error when rendering dependencies

---

components/Editor.js
utils/recursiveDependencyFetchWorker.js

Fixes a few scenarios where dependencies were not being detected or highlighted. Including:
https://deploy-preview-166--runpkg.netlify.com/
- Export statements like `export * from "./somewhere"` [example](https://runpkg.com/?@urql/exchange-graphcache@1.2.2/src/index.ts) -> [fix](https://deploy-preview-166--runpkg.netlify.com/?@urql/exchange-graphcache@1.2.2/src/index.ts)
- Import statements with no space like `import"./something.js"` [example](https://runpkg.com/?es-react@16.11.0/index.js) -> [fix](https://deploy-preview-166--runpkg.netlify.com/?es-react@16.11.0/index.js)
- Multiline import/export after destructuring [example](https://runpkg.com/?@urql/exchange-graphcache@1.2.2/src/operations/query.ts) -> [fix](https://deploy-preview-166--runpkg.netlify.com/?@urql/exchange-graphcache@1.2.2 …

Less specific import/export regex and smarter option choosing

---

components/Article.js

Adds Netlify badge to welcome screen, just below the "blurb" below the runpkg logo (#141)
I wasn't sure what the idiomatic way to use this `css` module. Is the way I've implemented it fine/preferred? I was leaning towards just having `.formidaLogo` and `.netlifyLogo` inside the `welcome:  css...` and then doing `className="formidaLogo"` and `className="netlifyLogo"` respectively, instead of `className=${styles.formidaLogo}` etc

Add Netlify badge to welcome screen > #141

---

CONTRIBUTING.md
README.md

Adds CoC (#138) and moves dev instructions over to a `CONTRIBUTING.md` (#174).
The CoC is a copy of the one used for both Victory and Spectacle, as per @ryan-roemer 's suggestion.
Have not added instructions/conventions for commits, branches and PRs as I think that requires group discussion!

Add CONTRIBUTING doc and include CoC > #174 #138

---

components/Main.js
index.html
utils/rplus.js

I noticed that the search was broken 👎 and previously was reached out to by Algolia who suggested that their search would be faster an more reliable. My only reservation was that it requires some credentials and an SDK.
But I was given some credentials and their SDK is available as a es module so I gave it a try and indeed it works almost exactly the same as the npms API but is better 🌈.
So unless anyone has an any reason we shouldn't use this service then I'd like to merge asap to get the site back up and functioning properly.

Swaps out npms search for algolia search

---

index.html

Seems like a quick win: avoids blocking `DOMContentLoaded`, resulting in the following performance enhancement (time to interactive (TTI) according to 3x runs of lighthouse desktop performance benchmark for me):
|Thing|TTI (ms)|Delta (ms)|
|---|---|---|
|No prettier|6200|-|
|Defer prettier|6833|+633|
|Async prettier|6567|+367|
So roughly a 266 ms improvement in TTI according to my non-statistically-significant testing

Prettier enhancement: make script async instead of defer

---

components/Main.js

This allows for easy usage analytics to be differentiated between this project and others on the same index.

feat(search): add analytics tags

---

components/Article.js
index.html

Marked version 4 has a breaking change that requires using `marked.parse(...)` instead of `marked(...)` - [Version 4.0.0 release notes](https://github.com/markedjs/marked/releases/tag/v4.0.0)
This PR just satisfies that requirement.
_-Note-_
Marked is currently included in the project using `<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>`.
Perhaps we should consider locking that to a major or minor version to avoid unexpected breaking changes in future?
(`<script src="https://cdn.jsdelivr.net/npm/marked@4/marked.min.js"></script>`)

fix: use `marked.parse` to satisfy breaking change in marked 4+

---

components/Editor.js

Fixes #194
By using `:before`, Firefox does not run into issues handling `user-select: none;` of the line number spans. Since the number display is now inside the `before`, the line counter was moved to a [CSS counter](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters).

Move line number to :before

---

components/Editor.js
index.html

Fixes https://github.com/FormidableLabs/runpkg/issues/213
Code returned from `prism-react-renderer?module` on unpkg was instructed to import react to `react@>=16.0.0` which resolved to `react@18.2.0` which was returning `Package react@18.2.0 does not contain an ES module`.
This was breaking the site entirely.
The site renders and looks to function correctly again.

Fix dependency trying to import react 18

---

components/Main.js

`npmjs.cf` has been deprecated: https://github.com/npmjs-cf/meta/issues/8
Since `registry.npmjs.org` also has CORS support now (https://github.com/npm/feedback/discussions/117#discussioncomment-2691120), the PR replaces `registry.npmjs.cf` with `registry.npmjs.org`.

Replace `registry.npmjs.cf` with `registry.npmjs.org`
