components/Editor.js, index.js
1. Imported Prism highlighting for Reason + JSON
=> ReasonJSONSyntaxSupport

components/Nav.js, index.js
Implements #45 
1.  Put version scraper of unpkg.com into index.js useEffect.
2.  Passed versions [] into nav.
3. Render each version as an option in a select.
4. Created useEffect + useState so when version changes, it is pushed to the history.
=> VersionPicker

README.md
Enhancement from #35
1. browser compatibility table for runpkg.com
=> browser-table #35

index.css
=> small highlight tweak to header

index.js
=> update document.title based on req.url or fetcherror

utils/recursiveDependencyFetch.js
I believe this fixes 💯 #100 💯 
Please confirm/have a click around for edge cases you think of
=> Restore FF and Safari compatibility: use constructor instead of public field

.prettierignore, components/Aside.js, components/Nav.js, components/NotFound.js, components/Overlay.js, components/Search.js, components/SearchIcon.js, index.css, index.js
Work in progress.
Yet to be done (possibly for (@kiraarghy on Fri 7 June?):
=> Add search

now.json
* added www.runpkg.com to alias, which should fix www. redirect.
=> fixWWWRedirect

components/ProjectBadge/index.css, index.css
- Logo now plays infinitely, not a single loop
- Introduces a delay between each animation loop so make it less 'Vegas'-y
- Updates button `cursor` style to `pointer`
=> Update splash screen logo animation

README.md
- Adds maintenance status to the README
- Updates README headings to h2 to make for a more logical heading hierarchy
=> Add maintenance status

index.js, serviceWorker.js
So I created a service worker using a `Cache only` strategy i.e. we pull from cache. This should be fine as with semver if we request a specific version it should never change. 
I got this working thanks to @lukejacksonn, this [thread](https://github.com/lukejacksonn/servor/issues/30) helped! 
This results in a load time that is significantly faster than a cold start!
No service worker:
Service worker:
=> Service worker re issue: #116

components/Article.js, components/Editor.js, components/FileOverview.js, components/Footer.js, components/Nav.js, components/PackageOverview.js, components/RadioGroup.js, components/RegistryOverview.js, utils/recursiveDependencyFetch.js
Some refinements on some of the newer features and dependency resolution.
=> Revisions and syntax highlighting based on extension

components/Nav.js, components/PackageOverview.js
- Updates the package file explorer to have a directory tree view design
- Fixes file search
- Displays a flat list of files when a search term is present, with their full path listed (instead of a tree view)
Looks a little something like this:
=> Update Package View

utils/recursiveDependencyFetch.js
Was breaking on `/?rplus@1.0.0/index.js` now is fixed 🎉
=> Fixes https imports linking

components/Article.js, components/Editor.js, components/FileOverview.js, components/Nav.js, components/PackageOverview.js, components/RadioGroup.js, components/RegistryOverview.js, index.html, package.json, reset.css, utils/recursiveDependencyFetchWorker.js
Fixes some issues that were found after merging the V1 branch.
=> Quick fixes

components/Article.js, components/FileOverview.js, components/PrettierIcon.js, index.html
=> Adds prettier standalone and button to invoke

components/PackageOverview.js, components/TreeView.js
This PR:
- creates abstract TreeView component for rendering a generic tree-style data structure
- updates PackageOverview to use this component for the file tree
- refactors some logic within PackageOverview for readability/clarity's sake
Hopefully this component is abstract enough to be used within a dependency tree further down the line.
=> Create abstract TreeView component

components/PackageOverview.js
Adds file path to file search results
=> Add full file path info to search results

index.html
=> Update og:image tags

components/PackageOverview.js
closes #188 
let me know if there is any feedback on how it look
=> (feat): Adds Document folder size
